### ISSUE TITLE
copy files only on version 7.0.HF and 7.1

### ISSUE THREAD

**Issue by Zeke-Zhang** [WicresoftMBSSE/NAVTool#11]
Sync Schema for   All tables with validation      (Before sync, start the NAV service.     Do this only for NAV80,NAV90,NAV10 & 

Copy files:   Update_Rollups\...\NST -> C:\Program Files\Microsoft Dynamics   NAV\70\Service              (Do this only for NAV70HF & NAV71)
Copy files:   Update_Rollups\...\WEB CLIENT -> C:\Program Files\Microsoft Dynamics   NAV\70\Web Client             (Do this only for NAV70HF & NAV71)
Copy files:   Update_Rollups\...\RTC -> C:\Program Files (x86)\Microsoft Dynamics   NAV\70\RoleTailored   Client             (Do this only for NAV70HF & NAV71)

In Object   Designer, import NAV.xxx.CUObjects.fob from   Update_Rollups\...\APPLICATION

在同步操作之后导入fob文件之前，在第一次解压CU压缩包生成的文件夹中
注：复制文件时NAV不能运行
1：NST文件夹下的所有文件复制到C:\Program Files\Microsoft Dynamics   NAV\70\Service
2：WEB CLIENT文件夹下的所有文件复制到 C:\Program Files\Microsoft Dynamics   NAV\70\Web Client
3：RTC文件夹下的所有文件复制到C:\Program Files (x86)\Microsoft Dynamics   NAV\70\RoleTailored   Client

**Comment by DonnyChen** [comment]
Done
