### ISSUE TITLE
check CaptionML, OptionCaptionsML, TextConst translation(do this before compare files)

### ISSUE THREAD

**Issue by Zeke-Zhang** [WicresoftMBSSE/NAVTool#13]
在Application\xxx.CUObjects.txt文件中
check CaptionML, OptionCaptionsML, TextConst translation like:
CaptionML=[ENU=Currency;
                     DEA=W„hrung];
OptionCaptionML=[ENU=Nearest,Up,Down;
                                DEA=Kaufm„nnisch,Aufrunden,Abrunden];
TextConst 'ENU=must be rounded to the nearest %1;DEA=muss kaufm„nnisch auf %1 gerundet werden';
检查是否翻译以及是否正确翻译为相应国家的语言

**Comment by DonnyChen** [comment]
Done
