### ISSUE TITLE
No Reginal Format for "IN".

### ISSUE THREAD

**Issue by chnmoon** [WicresoftMBSSE/NAVTool#17]
2018/01/29 15:27:34: Import file C:\NAVWorking\DynamicsNAV2016\IN\Extracted\APPLICATION\NAV.9.0.49968.IN.CUObjects.txt
Import-NAVApplicationObject : : [86573217] '04/24/16;' is not a valid date.
[0] The import stopped at line 5.

At D:\NAVTool-Donny\NAV\Import-FobOrTxtFile.ps1:73 char:13
+             Import-NAVApplicationObject @importParam
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject

      [-] Import txt file into DynamcisNAV2016 with IN 681ms
        Expected: file {C:\NAVWorking\Logs\ImportFobOrTxt\Txt
        avcommandresult.txt} to contain {The command completed successfully}
        374:                 $importTxtLog | Should -FileContentMatch $ExpectedCommandLog
        at Invoke-Assertion, C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.1\Functions\Assertions\Should.ps1: line 209
        at <ScriptBlock>, D:\NAVTool-Donny\Tests\RCL.Tests.ps1: line 374

**Comment by DonnyChen** [comment]
Fixed
