### ISSUE TITLE
There is a warning for NAV2015DE & NAV2015CH

### ISSUE THREAD

**Issue by GingerMM** [WicresoftMBSSE/NAVTool#37]
When compile txt file, there will be a warning as below, we can ignore it when testing.
---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
The object 'MenuSuite 1020 Dept - Region DACH' must be compiled before it can be run.
---------------------------
OK   
---------------------------
The picture is attached in onenote.

**Comment by DonnyChen** [comment]
Fixed
